{{- if .Values.mongodb.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  accessModes:
    - {{ .Values.mongodb.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | default "2Gi" }}
  {{- if .Values.mongodb.persistence.storageClassName }}
  storageClassName: {{ .Values.mongodb.persistence.storageClassName }}
  {{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    service: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: mongodb
        image: {{ .Values.image.repo }}/rs-mongodb:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 27017
        {{- if .Values.mongodb.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /data/db
        {{- end }}
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
      {{- if .Values.mongodb.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mongodb
      {{- end }}
      {{- with .Values.mongodb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
