{{- if .Values.rabbitmq.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  accessModes:
    - {{ .Values.rabbitmq.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.rabbitmq.persistence.size | default "2Gi" }}
  {{- if .Values.rabbitmq.persistence.storageClassName }}
  storageClassName: {{ .Values.rabbitmq.persistence.storageClassName }}
  {{- end }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      service: rabbitmq
  template:
    metadata:
      labels:
        service: rabbitmq
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: rabbitmq
        image: rabbitmq:3.7-management-alpine
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5672
        - containerPort: 15672
        {{- if .Values.rabbitmq.persistence.enabled }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        {{- end }}
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
      {{- if .Values.rabbitmq.persistence.enabled }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: rabbitmq
      {{- end }}
      {{- with .Values.rabbitmq.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitmq.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rabbitmq.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
